version: '3.8'
services:
  db:
    container_name: fullStack
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=fullStack
      - MYSQL_USER=fullstack
      - MYSQL_PASSWORD=fullstack
      - MYSQL_ROOT_PASSWORD=fullstack
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    ports:
      - '8080:8080'
    volumes:
      - target:/app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/fullStack
      - spring.main.web-application-type=none
      - DATABASE_HOST=db
      - DATABASE_NAME=fullStack
      - DATABASE_USER=fullstack
      - DATABASE_PASSWORD=fullstack
    links:
      - db

volumes:
  db:
  target:
